export function createExperimentParams() {
  return {
    caseId: 'F',
    ssgiEnabled: true,
    ssgiIntensity: 1,
    ssgiAoIntensity: 1,
    ssgiRadius: 2,
    ssgiThickness: 0.15,
    ssgiView: 'combined',
    toneMapping: 'filmic',
    exposure: 1,
    lightMapIntensity: Math.PI,
    directIntensity: 2.5,
    animateSun: false,
    dayNightTime: 0.32,
    probeIntensity: 1,
    probeBounces: 2,
    showProbeHelper: false,
    portalColor: '#7663ff',
    portalIntensity: 1.6,
    portalSpeed: 0.28,
    poleColor: '#ff4e18',
    poleIntensity: 3,
    poleFlameHeight: 1,
    poleFlameWidth: 1.5,
    poleFlameCore: 0.55,
  }
}
